name: CI

on:
  push:
    branches: [ breakout-game ]
  pull_request:
    branches: [ breakout-game ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-playwright
          python -m playwright install
          python -m playwright install-deps

      - name: Start Flask app in background
        run: |
          export FLASK_APP=app.py
          nohup flask run --host=0.0.0.0 &
          sleep 5

      - name: Run backend tests
        run: pytest tests/test_api.py

      - name: Run Playwright tests
        run: pytest tests/test_snake_overlay.py